// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the only bound service. Credentials and process internals never
 * become generated bindings; business packages know nothing about Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as authsync$0 from "./internal/authsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "./internal/scheduler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "./internal/usage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddAccount(name: string, authJSON: string): $CancellablePromise<store$0.AccountsState> {
    return $Call.ByID(2620387760, name, authJSON);
}

export function AddPendingCurrentAccount(pendingID: string, name: string): $CancellablePromise<store$0.AccountsState> {
    return $Call.ByID(3136421524, pendingID, name);
}

export function CheckAuthSyncNow(): $CancellablePromise<authsync$0.Status> {
    return $Call.ByID(4169648517);
}

export function ChooseAuthFile(): $CancellablePromise<$models.ChosenFile | null> {
    return $Call.ByID(1761100787);
}

export function Confirm(message: string, options: $models.ConfirmOptions): $CancellablePromise<boolean> {
    return $Call.ByID(3802682850, message, options);
}

export function DetectCodexCLIPath(): $CancellablePromise<string | null> {
    return $Call.ByID(2773836229);
}

export function GetAccountQuota(accountID: string): $CancellablePromise<usage$0.AccountQuotas> {
    return $Call.ByID(4129885391, accountID);
}

export function GetAccountQuotas(): $CancellablePromise<usage$0.AccountQuotas> {
    return $Call.ByID(1050610676);
}

export function GetAuthSyncStatus(): $CancellablePromise<authsync$0.Status> {
    return $Call.ByID(3684857433);
}

export function GetScheduledRunStatus(): $CancellablePromise<scheduler$0.RunStatus> {
    return $Call.ByID(1225651236);
}

export function GetSettings(): $CancellablePromise<scheduler$0.Settings> {
    return $Call.ByID(3018893939);
}

export function GetUsageStats(days: number, refreshPrices: boolean | null): $CancellablePromise<usage$0.UsageStats> {
    return $Call.ByID(2626047168, days, refreshPrices);
}

export function ListAccounts(): $CancellablePromise<store$0.AccountsState> {
    return $Call.ByID(1560646494);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(790318107, url);
}

export function RemoveAccount(accountID: string): $CancellablePromise<store$0.AccountsState> {
    return $Call.ByID(2210581393, accountID);
}

export function SaveSettings(settings: scheduler$0.Settings): $CancellablePromise<scheduler$0.Settings> {
    return $Call.ByID(3784651466, settings);
}

export function SwitchAccount(accountID: string): $CancellablePromise<store$0.AccountsState> {
    return $Call.ByID(3806381117, accountID);
}
