// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export interface BackupTransferResult {
    "filePath": string;
    "fileName": string;
    "accountCount": number;
}

export interface ChosenBackupFile {
    "filePath": string;
    "fileName": string;
}

export interface ChosenFile {
    "filePath": string;
    "fileName": string;
    "authJson": string;
}

export interface ConfirmOptions {
    "title": string;
    "kind": string;
}

export interface ImportAccountsResult {
    "state": store$0.AccountsState;
    "accountCount": number;
    "autoSyncDisabled": boolean;
}
