// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChosenFile {
    "filePath": string;
    "fileName": string;
    "authJson": string;
}

export interface ConfirmOptions {
    "title": string;
    "kind": string;
}
