// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountQuota {
    "accountId": string;
    "accountName": string;
    "ok": boolean;
    "planType": string | null;
    "primary": RateLimitWindow | null;
    "secondary": RateLimitWindow | null;
    "tertiary": RateLimitWindow | null;
    "fiveHour": RateLimitWindow | null;
    "weekly": RateLimitWindow | null;
    "monthly": RateLimitWindow | null;
    "credits": CreditsInfo | null;
    "fetchedAt": string | null;
    "error": string | null;
}

export interface AccountQuotas {
    "sourceUrl": string;
    "accounts": AccountQuota[] | null;
}

export interface CreditsInfo {
    "hasCredits": boolean;
    "unlimited": boolean;
    "balance": string | null;
}

export interface DailyUsageItem {
    "date": string;
    "totalTokens": number;
    "estimatedCostUsd": number;
}

export interface DisplayedPrice {
    "input": number;
    "cachedInput": number | null;
    "cacheWrite": number | null;
    "output": number;
}

export interface ModelUsageItem {
    "model": string;
    "inputTokens": number;
    "cachedInputTokens": number;
    "cacheWriteInputTokens": number;
    "outputTokens": number;
    "reasoningOutputTokens": number;
    "totalTokens": number;
    "modelCalls": number;
    "turnCount": number;
    "averageTokensPerTurn": number | null;
    "averageDurationMs": number | null;
    "averageTimeToFirstTokenMs": number | null;
    "estimatedCostUsd": number | null;
    "price": DisplayedPrice | null;
}

export interface PricingSource {
    "url": string;
    "fetchedAt": string;
    "kind": string;
    "modelCount": number;
    "warning": string | null;
}

export interface RateLimitWindow {
    "usedPercent": number;
    "windowMinutes": number | null;
    "resetsAt": number | null;
    "resetAfterSeconds": number | null;
}

export interface UsageStats {
    "generatedAt": string;
    "rangeDays": number;
    "sessionsDir": string;
    "pricingSource": PricingSource;
    "summary": UsageSummary;
    "models": ModelUsageItem[] | null;
    "daily": DailyUsageItem[] | null;
}

export interface UsageSummary {
    "inputTokens": number;
    "cachedInputTokens": number;
    "cacheWriteInputTokens": number;
    "outputTokens": number;
    "reasoningOutputTokens": number;
    "totalTokens": number;
    "sessions": number;
    "modelCalls": number;
    "estimatedCostUsd": number;
    "unpricedModelCount": number;
}
