// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountResult {
    "accountId": string;
    "accountName": string;
    "status": AccountStatus;
    "startedAt": string | null;
    "finishedAt": string | null;
    "message": string | null;
    "prompt": string | null;

    /**
     * nil means a legacy record; an empty string means no completed response yet.
     */
    "response": string | null;
}

export enum AccountStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Waiting = "waiting",
    Running = "running",
    Success = "success",
    Failed = "failed",
    Interrupted = "interrupted",
};

export interface BatchResult {
    "startedAt": string;
    "finishedAt": string | null;
    "accounts": AccountResult[] | null;
}

export interface RunStatus {
    "nextRunAt": string | null;
    "timezone": string;
    "running": boolean;
    "error": string | null;
    "lastRun": BatchResult | null;
}

export interface Settings {
    "enabled": boolean;
    "time": string | null;
    "cliPath": string | null;
}
