// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Disabled = "disabled",
    Checking = "checking",
    UpToDate = "up_to_date",
    Synced = "synced",
    Followed = "followed",
    Unknown = "unknown",
    Ambiguous = "ambiguous",
    Invalid = "invalid",
    Missing = "missing",
    Failed = "error",
};

export interface Status {
    "enabled": boolean;
    "state": State;
    "accountId": string | null;
    "accountName": string | null;
    "checkedAt": string | null;
    "syncedAt": string | null;
    "pendingId": string | null;
    "message": string | null;
}
