import { readFileSync } from 'node:fs';

export const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
export const wailsVersion = 'v3.0.0-beta.18';
const v = pkg.version;
if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(v)) throw new Error('Version must be MAJOR.MINOR.PATCH');
const plist = (development) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleExecutable</key><string>switch-codex</string>
<key>CFBundleIdentifier</key><string>com.switchcodex.app${development ? '.dev' : ''}</string>
<key>CFBundleName</key><string>Switch Codex</string>
<key>CFBundleDisplayName</key><string>Switch Codex</string>
<key>CFBundlePackageType</key><string>APPL</string>
<key>CFBundleShortVersionString</key><string>${v}</string>
<key>CFBundleVersion</key><string>${v}</string>
<key>CFBundleIconFile</key><string>icons</string>
<key>LSMinimumSystemVersion</key><string>12.0</string>
<key>LSApplicationCategoryType</key><string>public.app-category.utilities</string>
<key>NSHighResolutionCapable</key><true/>
${development ? '<key>NSAppTransportSecurity</key><dict><key>NSAllowsLocalNetworking</key><true/></dict>\n' : ''}</dict></plist>
`;
export function versionFiles() {
  return new Map([
    ['version.go', `// Code generated by scripts/sync-version.mjs; DO NOT EDIT.\npackage main\n\nconst appVersion = "${v}"\n`],
    ['build/darwin/Info.plist', plist(false)],
    ['build/darwin/Info.dev.plist', plist(true)],
    ['build/windows/info.json', JSON.stringify({fixed:{file_version:v},info:{'0000':{ProductVersion:v,CompanyName:'Switch Codex',FileDescription:'Switch Codex',LegalCopyright:'Copyright © 2026 Switch Codex',ProductName:'Switch Codex'}}}, null, 2)+'\n'],
    ['build/windows/version.nsh', `; Generated from package.json.\n!define APP_VERSION "${v}"\n`],
    ['build/windows/wails.exe.manifest', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <assemblyIdentity type="win32" name="com.switchcodex.app" version="${v}.0" processorArchitecture="*"/>
  <dependency><dependentAssembly><assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/></dependentAssembly></dependency>
  <asmv3:application><asmv3:windowsSettings>
    <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
    <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">permonitorv2,permonitor</dpiAwareness>
  </asmv3:windowsSettings></asmv3:application>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"><security><requestedPrivileges><requestedExecutionLevel level="asInvoker" uiAccess="false"/></requestedPrivileges></security></trustInfo>
</assembly>
`],
  ]);
}
