// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountItem {
    "id": string;
    "name": string;
    "createdAt": string;
    "updatedAt": string;
    "authPath": string;
    "isActive": boolean;
}

export interface AccountsState {
    "dataDir": string;
    "targetAuthPath": string;
    "activeAccountId": string | null;
    "accounts": AccountItem[] | null;
}
